### ISSUE TITLE
Specificity of Product

### ISSUE THREAD

**Issue by Nhildenbrand19** [Dnisde/EC_601#3]
The only other thing I would suggest is at the beginning of your README, putting exactly what the product you are creating is doing. I know you put that it is an intro to a Social Media Analyzing program but what exactly will that program do when you make a product of it.

**Comment by Dnisde** [comment]
Dear Niko:

Thank you for your response anyway. I am going to modify the readme page
and upload the most recent update for the APP that I got so far. If
possible, I would let you know when I finish it.


Regard,
Zhaozhong QI
